service: CryptocurrencyPortfolioAPI

provider:
  name: aws
  runtime: nodejs8.10

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  createPortfolio:
    handler: portfolioService.createPortfolio
    events:
      - http:
          path: createPortfolio
          method: post
    environment:
      stage: ${self:provider.stage}
      table: ${self:resources.Resources.portfoliosTable.Properties.TableName}

resources:
 Resources:
   portfoliosTable:
     Type: AWS::DynamoDB::Table
     Properties:
       TableName: portfoliosTable_${self:provider.stage}
       BillingMode: PAY_PER_REQUEST
       AttributeDefinitions:
        - AttributeName: identifierHash
          AttributeType: S
       KeySchema:
          - AttributeName: identifierHash
            KeyType: HASH
 Outputs:
    portfoliosTableArn:
      Description: The ARN for the portfolio table
      Value:
        "Fn::GetAtt": [ portfoliosTable, Arn ]
