service: CryptocurrencyPortfolioAPI

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  iamRoleStatements:
     - Effect: "Allow"
       Action:
         - "dynamodb:UpdateItem"
         - "dynamodb:PutItem"
       Resource: "*"

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  createPortfolio:
    handler: portfolioService.createPortfolio
    events:
      - http:
          path: createPortfolio
          method: post
    environment:
      stage: ${self:provider.stage}
      table: ${self:resources.Resources.portfoliosTable.Properties.TableName}

resources:
 Resources:
   portfoliosTable:
     Type: AWS::DynamoDB::Table
     Properties:
       TableName: portfoliosTable_${self:provider.stage}
       BillingMode: PAY_PER_REQUEST
       AttributeDefinitions:
        - AttributeName: identifierHash
          AttributeType: S
       KeySchema:
          - AttributeName: identifierHash
            KeyType: HASH
 Outputs:
    portfoliosTableArn:
      Description: The ARN for the portfolio table
      Value:
        "Fn::GetAtt": [ portfoliosTable, Arn ]
